### PR TITLE
fix: Admin bookings query adjustment

### PR DESCRIPTION
**Pull request by Flashmaxi**

### CODE REVIEW

**Comment by trigger-xyz** [comment]
Could we add a message "No bookings ..." ? (see with muriel for figma and wording)
image

Also I have errors in my console 

image

**Comment by trigger-xyz** [comment]
Yes

**Comment by Flashmaxi** [comment]
> Yes

I removed the error messages and I added message in case there are no bookings. Asked on figma but it can take a while so we can merge my message and later it can be replaced with different sentence. @trigger67

**Comment by trigger-xyz** [comment]
Hey, is this normal that bookings are linked to my own personnal events ? 
Should'nt it display all events ??

**Comment by trigger-xyz** [comment]
+ many displayed dates are wrong.
Ex: this one is not in may
image

**Comment by Flashmaxi** [comment]
> * many displayed dates are wrong.
>   Ex: this one is not in may
>   image

**Comment by Flashmaxi** [comment]
> * many displayed dates are wrong.
>   Ex: this one is not in may
>   image

Not sure how did you achieve that it is past date/event and I tried testing with different dates. Every time it rendered the correct date. I will move it to draft and try to recreate that behavior.

**Comment by trigger-xyz** [comment]
Maybe it's linked to my browser language ?

**Comment by Flashmaxi** [comment]
> Maybe it's linked to my browser language ?

Not sure, I will work on this tonight to see why is that happening. Did you do smth differently with yml file?

**Comment by trigger-xyz** [comment]
Hey, I think it's a mistake on my side. I did not refresh my backend after you updated the code, so the date seems good finally.

**Comment by trigger-xyz** [comment]
Same format as we have on the curriculum would have been easier to read  ^^' (I have language in american in my OS) 
image

**Review by trigger-xyz — CHANGES_REQUESTED** [review]
A lot of bookings are missing now.
Hint: things are missing in your new query.

**Comment by trigger-xyz** [comment]
Hey, I bought a TechSchool (btc402) and booked seats to futur chapters.

And still I have `There are no upcoming bookings.` in the bookings page.

**Comment by trigger-xyz** [comment]
Tested it, works fine but I found one bug : 
- I created a paid event (not a course chapter, a real event) => `DATA_REPOSITORY_BRANCH=trigger-paid`
- I booked the event with one account
- When I click on download list, I see `There are no participants for this event!`

**Pull request merged**
