### PR TITLE
feat(front): Add Lexique page 

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Comment by ssakone** [comment]
Hi, @louneskmt I'd like to know about the markdown data model, if you have an existing parsing model that you'd like me to use or if you'd like me to set up functions to directly parse and index the various words.

**Comment by ssakone** [comment]
It seems like the parsing function should be in the backend. I am currently trying to understand everything, but I may need more time. Alternatively, if another team member could help me understand the structure, that would be great. At the moment, the only thing missing to complete the task is the API endpoint to fetch lexical data.

**Comment by louneskmt** [comment]
You should add a new postgres table for the lexicon. Then in the content package, add logic to parse the incoming files and save the words to the database. Check the other folders in the content package for examples on how I import other types of content.

**Comment by louneskmt** [comment]
Did you make some progress on this?

**Comment by trigger67** [comment]
Hey, this is in standby because the glossary is not finished and open-sourced yet.
I created a branch here, to update later on : https://github.com/DecouvreBitcoin/sovereign-university/tree/glossary 

Thank you

**Pull request closed without merging**
